name: CI / Snapshot

on:
    push:
        branches:
            - main
            - 'feature/**'
            - 'bug/**'
            - 'fix/**'
            - 'hotfix/**'
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    snapshot:
        uses: oberon-oss/github-workflows/.github/workflows/maven-snapshot.yml@c9c6403eae7cddcf889156da0aa9ddffda296e58
        with:
            java-version: '25'
            snapshot-branch: ${{ github.ref_name }}
            sonar-enabled: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
            sonar-maven-profile: coverage
            sonar-quality-gate-blocking: false
            snapshot-maven-profiles: generate-javadoc-and-source
            sonar-project-key: ???
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
            CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}